name: ColonyMail
main: com.github.schmidtbochum.colonymail.ColonyMailPlugin
version: 0.0.1-SNAPSHOT
depend: [ColonyData]
commands:
  mail:
    description: Send and receive server mails.
    permission: colony.mail.command.mail
    usage: "/mail <read|send|clear|groupsend>"
permissions:
  colony.command.mail.send:
    description: Send mails
    default: op
  colony.command.mail.groupsend:
    description: Send mails to groups
    default: op
  colony.command.mail.read:
    description: Read mails
    default: op
  colony.command.mail.clear:
    description: Clear inbox
    default: op
  colony.mail.useformat:
    description: Use color/format codes in mails
    default: op